### ISSUE TITLE
Broken images on rpi 1 b+

### ISSUE THREAD

**Issue by iago1460** [linuxserver/docker-duckdns#20]
the last two docker images 958c387b-ls17 and a9bb5547-ls16 are now working (at least on the rpi)

```duckdns    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
duckdns    | [s6-init] ensuring user provided files have correct perms...exited 0.
duckdns    | [fix-attrs.d] applying ownership & permissions fixes...
duckdns    | [fix-attrs.d] done.
duckdns    | [cont-init.d] executing container initialization scripts...
duckdns    | [cont-init.d] 10-adduser: executing...
duckdns    | [cont-init.d] 10-adduser: exited 267.
duckdns    | [cont-finish.d] executing container finish scripts...
duckdns    | [cont-finish.d] done.
duckdns    | [s6-finish] waiting for services.
duckdns    | [s6-finish] sending all processes the TERM signal.
duckdns    | [s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by aptalca** [comment]
Post the command you used to create the container.

Which rpi is it?

Which os?

**Comment by iago1460** [comment]
I am using a ~~rpi 2~~  rpi 1 b+ with [hypriotos Version 1.10.0](https://github.com/hypriot/image-builder-rpi)

```
$ uname -a
Linux assistant 4.14.98+ #1200 Tue Feb 12 20:11:02 GMT 2019 armv6l GNU/Linux
```


I am running docker-compose but I don't think the issue is in my setup (I tried different combinations)

```
version: '3'
services:
  duckdns:
    image: linuxserver/duckdns:2a23692d-ls15
    container_name: duckdns
    environment:
      - TZ=Europe/London
      - SUBDOMAINS=$DUCKDNS_SUBDOMAIN
      - TOKEN=$DUCKDNS_TOKEN
    restart: unless-stopped
```

````
$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:42:54 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:38:25 2019
  OS/Arch:          linux/arm
  Experimental:     false
