### ISSUE TITLE
Cannot get a working instance on Raspberry Pi 3b

### ISSUE THREAD

**Issue by RemakingEden** [linuxserver/docker-duckdns#23]
First thanks for all your work. This is a great way for me to run my DDNS instance once I get it working :)

Hardware - Raspberry Pi 3b
Software - Rapsbian Buster latest

Steps to replicate:
Prerequisites : Docker & Raspbian Buster Lite
1. Execute the command laid out in the readme
```
docker create \
  --name=duckdns \
  -e PUID=1000  \
  -e PGID=1000  \
  -e TZ=Europe/London \
  -e SUBDOMAINS=mysubdomain \
  -e TOKEN=mytoken \
  --restart unless-stopped \
  linuxserver/duckdns:arm32v7-latest
```
2, Execute the command to start the container
```
docker start duckdns
```

Expected results:
A working container that updates my duckdns with my current ip

Actual results:
A container that does not appear to do anything

Docker logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-config: executing...
Retrieving subdomain and token from the environment variables
log will be output to docker log
Something went wrong, please check your settings  Wed Aug 7 00:35:07 BST 2019
[cont-init.d] 40-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
`Something went wrong, please check your settings  Wed Aug 7 00:35:07 BST 2019`

Either your subdomain or token is entered incorrectly

**Comment by RemakingEden** [comment]
@aptalca I copy and pasted them both in directly from DuckDNS. Is there any specific way they need to be written?

**Comment by aptalca** [comment]
Make sure the copy paste didn't add any invisible characters and make sure you put in the entire token.

Every time someone had the same issue, it's because they either omitted some part of the token, or they removed the dashes or something like that

**Comment by RemakingEden** [comment]
> Make sure the copy paste didn't add any invisible characters and make sure you put in the entire token.
> 
> Every time someone had the same issue, it's because they either omitted some part of the token, or they removed the dashes or something like that

I have just tried typing the token and subdomain by hand and I still get the same issue. I have also tried it on docker-compose and got the same issue. I'm very stuck on ideas at this point. Do you have a pi yourself that you could try and replicate on by any chance?

**Comment by aptalca** [comment]
Without seeing your exact values, I don't know what to tell you. Feel free to join our discord where you can pm me your screenshots and then change your token

**Comment by RemakingEden** [comment]
Perfect, i'll do that :) Thanks

**Comment by RemakingEden** [comment]
Finally got to the bottom of this.

For some reason I needed to specify the dns. I did this by adding dns to the command e.g.
```
docker create \
  --name=duckdns \
  --dns=1.1.1.1 \
  -e PUID=1000  \
  -e PGID=1000  \
  -e TZ=Europe/London \
  -e SUBDOMAINS=mysubdomain \
  -e TOKEN=mytoken \
  --restart unless-stopped \
  linuxserver/duckdns:arm32v7-latest
```
or in docker-compose
```
---
version: "2"
services:
  duckdns:
    image: linuxserver/duckdns:arm32v7-latest
    container_name: duckdns
    dns: 1.1.1.1
    environment:
      - PUID=1001 #optional
      - PGID=1001 #optional
      - TZ=Europe/London
      - SUBDOMAINS=mysubdomain
      - TOKEN=mytoken
    restart: unless-stopped
```

I am using Unbound and Pihole on this same Pi so this may be causing issue.

I hope this helps anyone with the same issue.

**Comment by erramon** [comment]
The same is happening to me. With docker-compose on a raspberry 3b + and with only duckdns configured.
I have tried updating libseccomp with no luck.
Any help is welcome

**Comment by techkujaku** [comment]
> The same is happening to me. With docker-compose on a raspberry 3b + and with only duckdns configured.
> I have tried updating libseccomp with no luck.
> Any help is welcome


i got mine working on a pi4 with this

```
---
version: "2.1"
services:
  duckdns:
    image: linuxserver/duckdns:arm32v7-latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ='Asia\Kuala Lumpur'
      - SUBDOMAINS=yourduckdnsdomain #without the .duckdns.org
      - TOKEN= get this from duck dns site
      - LOG_FILE=false #optional
    volumes:
      - /config/duckdns:/config  #/config/duckdns will depend on where you want the folder to be
    restart: unless-stopped
```
next go into your router and do some port forwarding.
For example my pi4 ip is 192.168.1.2 and i want to access home assistant running on port 8888
so in my router set up port forwarding. You might need to copy the WAN IP in your router and paste it into duckdns page and click on update IP. After that open a browser and type http://yourduckdnsdomain.duckdns.org:8888/

i am running from portainer and i get this error from the logs

<h1>Bad Message 400</h1><pre>reason: Illegal character SPACE=' '</pre>,
Something went wrong, please check your settings Fri Jul 16 02:22:02  2021,
[services.d] starting services

It seems to be working though but i need to manually update the ip in duckdns when my WAN ip changes. probably something went wrong or i will need a cronjob to update it
