### ISSUE TITLE
Multiple subdomains issue

### ISSUE THREAD

**Issue by MathieuJouslin** [linuxserver/docker-duckdns#37]
I have an error with my two subdomains :
_Output : Something went wrong, please check your settings  Thu Apr 29 19:10:01 CEST 2021_

When I put just one domain it's ok but two it does'nt work.

### My configuration : 
```
version: "2.1"
services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Paris
      - SUBDOMAINS=test1,test2
      - TOKEN=***********
      - LOG_FILE=true
    volumes:
      - /srv/dev-disk-by-label-DATA/config/duckdns:/config 
    restart: unless-stopped
```
