### ISSUE TITLE
[BUG] Defining FILE__TOKEN doesn't work

### ISSUE THREAD

**Issue by MagicLegend** [linuxserver/docker-duckdns#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've switched from an AMD64 system to an ARM system, and now the configuration I had for the container no longer works:

```
version: "2.1"
secrets:
  duckdns_token:
    file: ./duckdns_token.txt
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    secrets:
      - duckdns_token
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Amsterdam
      - SUBDOMAINS=mydomain
      - FILE__TOKEN=/run/secrets/duckdns_token
      - LOG_FILE=false #optional
    # volumes:
    #   - /path/to/appdata/config:/config #optional
    restart: unless-stopped
```

Where `./duckdns_token.txt` is a `root` owned `600` permissions file containing the token without a newline. When I get a shell in the container I see that the secrets file is set, but the environment variable is set to an empty line:

![image](https://github.com/user-attachments/assets/fc599e44-0cbb-4bb7-8053-e239add48483)

### Expected Behavior

The `TOKEN` env variable is set, as per the documentation at https://docs.linuxserver.io/images/docker-duckdns/?h=duckdns#environment-variables-from-files-docker-secrets

### Steps To Reproduce

I'm not quite sure, but the issue appeared for me when I switched from an AMD64 system to an ARM (`aarch64`) system.

### Environment

```markdown
- OS: Ubuntu 24.04
- How docker service was installed: apt
```

### CPU architecture

arm64

### Docker creation

```bash
`docker compose up -d`
```

### Container logs

```bash
duckdns  | [migrations] started
duckdns  | [migrations] no migrations found
duckdns  | [env-init] Your secret: FILE__TOKEN
duckdns  |            contains a trailing newline and may not work as expected
duckdns  | [env-init] TOKEN set from FILE__TOKEN
duckdns  | ───────────────────────────────────────
duckdns  |
duckdns  |       ██╗     ███████╗██╗ ██████╗
duckdns  |       ██║     ██╔════╝██║██╔═══██╗
duckdns  |       ██║     ███████╗██║██║   ██║
duckdns  |       ██║     ╚════██║██║██║   ██║
duckdns  |       ███████╗███████║██║╚██████╔╝
duckdns  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
duckdns  |
duckdns  |    Brought to you by linuxserver.io
duckdns  | ───────────────────────────────────────
duckdns  |
duckdns  | To support the app dev(s) visit:
duckdns  | DuckDNS: https://www.patreon.com/user?u=3209735
duckdns  |
duckdns  | To support LSIO projects visit:
duckdns  | https://www.linuxserver.io/donate/
duckdns  |
duckdns  | ───────────────────────────────────────
duckdns  | GID/UID
duckdns  | ───────────────────────────────────────
duckdns  |
duckdns  | User UID:    1000
duckdns  | User GID:    1000
duckdns  | ───────────────────────────────────────
duckdns  | Linuxserver.io version: 245f78ab-ls26
duckdns  | Build-date: 2024-07-15T04:01:42+00:00
duckdns  | ───────────────────────────────────────
duckdns  |
duckdns  | Detecting IPv4 via DuckDNS
duckdns  | curl: (3) URL rejected: Malformed input to a URL function
duckdns  | Something went wrong, please check your settings Thu Aug  1 11:42:11 CEST 2024
duckdns  | The response returned was:
duckdns  |
duckdns  |
duckdns  | [custom-init] No custom files found, skipping...
duckdns  | [ls.io-init] done.
```
